const landpoint.mine = "mine [stat]sodium [white]for build majority of the buildings"
const landpoint.drillinfo = "[stat]sodium drills [white]can mine []sodium []research them in the research tree"
const landpoint.drillplace = "place [stat]sodium drills [white]to mine []sodium"
const landpoint.conveyorplin = "research [stat] sodium conveyor and use them to guide the way from [stat]sodium drills [white]to []core Unity [white]for transport [stat]sodium"
const landpoint.attack = "attack the [red]enemy core [white] with your [stat]core unit []* In B3, you will not be able to attack the enemy's core with a core unit. *"